graphql:
  packages:
    - "com.queckly.app.service"
    - "com.queckly.app.controller"
    - "com.queckly.app.controller.dto"

okta:
  oauth2:
    issuer: ${okta-issuer}
    client-id: ${okta-client-id}
    client-secret: ${okta-client-secret}
    redirect-uri: ${okta-redirect-uri}
    scope: openid,profile,email
  client:
    token: ${okta-api-token}
  resourceserver:
    jwt:
      jwk-set-uri: ${okta-jwk}

rabbitmq:
  host: localhost
  port: 5672
  username: guest
  password: guest

#logging:
#  level:
#    org:
#      springframework: DEBUG

