graphql:
  packages: "com.queckly.app.controller"

auth0:
  audience: https://dev-80565895.okta.com

spring:
  security:
    oauth2:
      client:
        provider:
          okta:
            issuer-uri: ${okta-issuer}
        registration:
          okta:
            client-id: ${okta-client-id}
            client-secret: ${okta-client-secret}
            redirect-uri: ${okta-redirect-uri}
            scope: openid,profile,email

logging:
  level:
    org:
      springframework:
        security: DEBUG
